# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
  node: circleci/node@5.1.0

workflows:
  main:
    jobs:
      - test:
          version: '18.17'
      - test:
          version: '20.5'

jobs:
  test:
    parameters:
      version:
        type: string
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: << parameters.version >>
      - run: npm install coveralls --no-save
      - node/run:
          npm-run: lint
      - node/run:
          npm-run: citest
      - coveralls/upload:
          path_to_lcov: ./coverage/lcov.info
